apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-svc
  namespace: {{ .Values.app.namespace }}
  labels:
  {{- include "ui.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: {{ .Values.app.nodeport }} 
  selector:
    app: hello-world
  type: NodePort


 
